version: '3'
services: #Angabe aller Services
  asi: # Sample Microservice
    build: . # Der Service basiert auf einer Dockerfile in dem directory "."
    depends_on: # Der Service wartet auf den Start der DB.
    - asi_db
    networks: # Netzwerk für die DB und dem Microservice
    - fae-team-2-bezugsperson_asi_ms_db
    - fae-message-broker_kafka-broker_backend
    ports: # Ports des Service die an die Host-Maschine übertragen werden.
    - 8021:8021
  # Spezifikation der Datenbank
  asi_db: # Sample DB
    image: postgres:10.1 # Basis Image
    volumes:
    - asi_db:/var/lib/postgresql/data # Volume um Daten persistent zu speichern. Alle Daten aus dem Pfad (rechts) werden in das Volume abgelegt.
    environment: # Konfiguration über env-Variablen
    - POSTGRES_PASSWORD=_asi_Service_2018
    - POSTGRES_USER=asiService
    - POSTGRES_DB=asiService
    - PGDATA=/var/lib/postgresql/data/pgdata
    - JAVA_TOOL_OPTIONS=-Xms128m -Xmx256m
    restart: always # Bei einem Abstaurz soll die DB immer neu starten.
    networks: # Netzwerk für die DB und dem Microservice
    - fae-team-2-bezugsperson_asi_ms_db
volumes: # Allgemeine Volumes für das Projekt
  asi_db: {}
networks: # Allgemeine Netzwerke für das Projekt
  fae-team-2-bezugsperson_asi_ms_db:
    driver: bridge
  fae-message-broker_kafka-broker_backend:
    external: true